--USERS TABLE
CREATE TABLE USERS 
  (     
     EMPLOYEEID     NVARCHAR(30), 
     FULLNAME       NVARCHAR(240) NOT NULL, 
     RECEIPTNAME    NVARCHAR(30), 
     IS_ACTIVE      BIT NOT NULL, 
     WORKGROUPID    NVARCHAR(30) NOT NULL,
     PRIMARY KEY (EMPLOYEEID)
  ); 
  
  
-- CHILD TABLE
CREATE TABLE STORE_USER_SWIPE_CARDS 
  ( 
     EMPLOYEEID        NVARCHAR(30), 
     CARDNUMBER        NVARCHAR(8), 
     CARDEFFECTIVEFROM DATETIME, 
     CARDEFFECTIVETO   DATETIME,
	 PRIMARY KEY (CARDNUMBER),	 
     FOREIGN KEY (EMPLOYEEID) REFERENCES USERS(EMPLOYEEID) 
  ); 
  

-- USER CHANGE AUDIT TABLE
CREATE TABLE USER_CHANGE_AUDIT
	(
		CHANGE_ID      NVARCHAR(36),
		EMPLOYEEID     NVARCHAR(30),
		PRIMARY KEY (CHANGE_ID, EMPLOYEEID),
		FOREIGN KEY (EMPLOYEEID) REFERENCES USERS(EMPLOYEEID)
	);